name: Lint

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "v*"
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  super-linter:
    name: Super Linter
    uses: harryzcy/github-actions/.github/workflows/linter.yml@2b6b19fc1e4fa82e5ed7be70baeb27e2526f1a07 # main

  rust-fmt:
    name: Rust Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Set up Rust
        run: |
          rustup update stable && rustup default stable
      
      - name: Install rustfmt
        run: rustup component add rustfmt

      - name: Run rustfmt
        run: cargo fmt --all -- --check

  rust-clippy:
    name: Rust Clippy
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        toolchain:
          - stable
          - nightly
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Set up Rust
        run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}

      - name: Install Clippy
        run: rustup component add clippy

      - name: Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
        env:
          CARGO_INCREMENTAL: "0"

  rust-machete:
    name: Rust Machete
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Machete
        uses: bnjbvr/cargo-machete@ac30a525c0a8d163a92d727b3ff079ee3f6ecb08 # v0.9.2

  spelling:
    name: Spelling
    uses: harryzcy/github-actions/.github/workflows/spelling.yml@2b6b19fc1e4fa82e5ed7be70baeb27e2526f1a07 # main
